<?php

namespace AppBundle\Repository;

/**
 * SnipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnipeRepository extends \Doctrine\ORM\EntityRepository
{
}
